package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Rishab-Kumar-R/nano-faas/gateway/graph/model"
	"github.com/redis/go-redis/v9"
)

var rdb = redis.NewClient(&redis.Options{
	Addr: "localhost:6379",
})

const JobQueue = "job_queue"

// CreateFunction is the resolver for the createFunction field.
func (r *mutationResolver) CreateFunction(ctx context.Context, name string, language model.Language, code string) (*model.Function, error) {
	id := fmt.Sprintf("func-%d", time.Now().Unix())

	newFunc := &model.Function{
		ID:        id,
		Name:      name,
		Language:  language,
		Code:      code,
		CreatedAt: time.Now().Format(time.RFC3339),
	}

	data, _ := json.Marshal(newFunc)

	err := rdb.HSet(ctx, "function:"+id, "meta", data).Err()
	if err != nil {
		return nil, fmt.Errorf("failed to save function: %v", err)
	}

	task := map[string]string{
		"id":       id,
		"language": newFunc.Language.String(),
		"code":     newFunc.Code,
	}

	taskJSON, _ := json.Marshal(task)
	err = rdb.RPush(ctx, JobQueue, taskJSON).Err()
	if err != nil {
		return nil, fmt.Errorf("failed to queue job: %v", err)
	}

	fmt.Printf("Job Queued: %s\n", id)
	return newFunc, nil
}

// RunFunction is the resolver for the runFunction field.
func (r *mutationResolver) RunFunction(ctx context.Context, functionID string) (*model.Execution, error) {
	panic(fmt.Errorf("not implemented: RunFunction - runFunction"))
}

// Functions is the resolver for the functions field.
func (r *queryResolver) Functions(ctx context.Context) ([]*model.Function, error) {
	keys, err := rdb.Keys(ctx, "function:*").Result()
	if err != nil {
		return nil, err
	}

	var allFunctions []*model.Function

	for _, key := range keys {
		val, err := rdb.HGet(ctx, key, "meta").Result()
		if err == nil {
			var f model.Function
			json.Unmarshal([]byte(val), &f)
			allFunctions = append(allFunctions, &f)
		}
	}

	return allFunctions, nil
}

// Execution is the resolver for the execution field.
func (r *queryResolver) Execution(ctx context.Context, id string) (*model.Execution, error) {
	panic(fmt.Errorf("not implemented: Execution - execution"))
}

// FunctionLogs is the resolver for the functionLogs field.
func (r *subscriptionResolver) FunctionLogs(ctx context.Context, executionID string) (<-chan *model.Log, error) {
	panic(fmt.Errorf("not implemented: FunctionLogs - functionLogs"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
