package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Rishab-Kumar-R/nano-faas/gateway/graph/model"
	"github.com/Rishab-Kumar-R/nano-faas/shared"
	"github.com/google/uuid"
	"github.com/robfig/cron/v3"
)

const jobQueue = "job_queue"

// CreateFunction is the resolver for the createFunction field.
func (r *mutationResolver) CreateFunction(ctx context.Context, name string, language model.Language, code string) (*model.Function, error) {
	id := uuid.NewString()

	fn := &model.Function{
		ID:        id,
		Name:      name,
		Language:  language,
		Code:      code,
		CreatedAt: time.Now().Format(time.RFC3339),
	}

	data, err := json.Marshal(fn)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize function: %v", err)
	}

	if err := r.Redis.HSet(ctx, "function:"+id, "meta", data).Err(); err != nil {
		return nil, fmt.Errorf("failed to save function: %v", err)
	}

	return fn, nil
}

// UpdateFunction is the resolver for the updateFunction field.
func (r *mutationResolver) UpdateFunction(ctx context.Context, id string, name *string, code *string) (*model.Function, error) {
	val, err := r.Redis.HGet(ctx, "function:"+id, "meta").Result()
	if err != nil {
		return nil, fmt.Errorf("function not found")
	}

	var fn model.Function
	if err := json.Unmarshal([]byte(val), &fn); err != nil {
		return nil, fmt.Errorf("failed to parse function: %v", err)
	}

	if name != nil {
		fn.Name = *name
	}
	if code != nil {
		fn.Code = *code
	}

	data, err := json.Marshal(fn)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize function: %v", err)
	}

	if err := r.Redis.HSet(ctx, "function:"+id, "meta", data).Err(); err != nil {
		return nil, fmt.Errorf("failed to update function: %v", err)
	}

	return &fn, nil
}

// DeleteFunction is the resolver for the deleteFunction field.
func (r *mutationResolver) DeleteFunction(ctx context.Context, id string) (bool, error) {
	pipe := r.Redis.Pipeline()
	pipe.Del(ctx, "function:"+id)
	pipe.Del(ctx, "executions:"+id)
	if _, err := pipe.Exec(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// RunFunction is the resolver for the runFunction field.
func (r *mutationResolver) RunFunction(ctx context.Context, functionID string, input *string) (*model.Execution, error) {
	val, err := r.Redis.HGet(ctx, "function:"+functionID, "meta").Result()
	if err != nil {
		return nil, fmt.Errorf("function not found: %v", err)
	}

	var fn model.Function
	if err := json.Unmarshal([]byte(val), &fn); err != nil {
		return nil, fmt.Errorf("failed to parse function: %v", err)
	}

	execID := uuid.NewString()

	pipe := r.Redis.Pipeline()
	pipe.HSet(ctx, "execution:"+execID,
		"id", execID,
		"functionId", functionID,
		"status", string(model.StatusQueued),
	)
	pipe.Expire(ctx, "execution:"+execID, 24*time.Hour)
	pipe.LPush(ctx, "executions:"+functionID, execID)
	pipe.Expire(ctx, "executions:"+functionID, 24*time.Hour)
	if _, err := pipe.Exec(ctx); err != nil {
		return nil, fmt.Errorf("failed to save execution: %v", err)
	}

	job := shared.JobPayload{
		ExecutionID: execID,
		FunctionID:  functionID,
		Language:    fn.Language.String(),
		Code:        fn.Code,
	}
	if input != nil {
		job.Input = *input
	}

	jobData, err := json.Marshal(job)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize job: %v", err)
	}

	if err := r.Redis.RPush(ctx, jobQueue, jobData).Err(); err != nil {
		return nil, fmt.Errorf("failed to queue job: %v", err)
	}

	return &model.Execution{
		ID:         execID,
		FunctionID: functionID,
		Status:     model.StatusQueued,
	}, nil
}

// ScheduleFunction is the resolver for the scheduleFunction field.
func (r *mutationResolver) ScheduleFunction(ctx context.Context, functionID string, cronExpr string) (*model.Schedule, error) {
	if _, err := r.Redis.HGet(ctx, "function:"+functionID, "meta").Result(); err != nil {
		return nil, fmt.Errorf("function not found")
	}

	// Validate cron expression before storing.
	p := cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)
	if _, err := p.Parse(cronExpr); err != nil {
		return nil, fmt.Errorf("invalid cron expression: %v", err)
	}

	id := uuid.NewString()

	pipe := r.Redis.Pipeline()
	pipe.HSet(ctx, "schedule:"+id, "id", id, "functionId", functionID, "cron", cronExpr)
	pipe.SAdd(ctx, "schedules", id)
	if _, err := pipe.Exec(ctx); err != nil {
		return nil, fmt.Errorf("failed to save schedule: %v", err)
	}

	r.Redis.Publish(ctx, "schedules:changed", "created:"+id)

	return &model.Schedule{ID: id, FunctionID: functionID, Cron: cronExpr}, nil
}

// DeleteSchedule is the resolver for the deleteSchedule field.
func (r *mutationResolver) DeleteSchedule(ctx context.Context, id string) (bool, error) {
	pipe := r.Redis.Pipeline()
	pipe.SRem(ctx, "schedules", id)
	pipe.Del(ctx, "schedule:"+id)
	if _, err := pipe.Exec(ctx); err != nil {
		return false, err
	}

	r.Redis.Publish(ctx, "schedules:changed", "deleted:"+id)
	return true, nil
}

// Functions is the resolver for the functions field.
func (r *queryResolver) Functions(ctx context.Context) ([]*model.Function, error) {
	keys, err := r.Redis.Keys(ctx, "function:*").Result()
	if err != nil {
		return nil, err
	}

	var functions []*model.Function
	for _, key := range keys {
		val, err := r.Redis.HGet(ctx, key, "meta").Result()
		if err != nil {
			continue
		}
		var fn model.Function
		if err := json.Unmarshal([]byte(val), &fn); err != nil {
			continue
		}
		functions = append(functions, &fn)
	}

	return functions, nil
}

// Execution is the resolver for the execution field.
func (r *queryResolver) Execution(ctx context.Context, id string) (*model.Execution, error) {
	vals, err := r.Redis.HGetAll(ctx, "execution:"+id).Result()
	if err != nil || len(vals) == 0 {
		return nil, fmt.Errorf("execution not found")
	}

	exec := &model.Execution{
		ID:         vals["id"],
		FunctionID: vals["functionId"],
		Status:     model.Status(vals["status"]),
	}
	if result, ok := vals["result"]; ok && result != "" {
		exec.Result = &result
	}

	return exec, nil
}

// ExecutionsByFunction is the resolver for the executionsByFunction field.
func (r *queryResolver) ExecutionsByFunction(ctx context.Context, functionID string) ([]*model.Execution, error) {
	execIDs, err := r.Redis.LRange(ctx, "executions:"+functionID, 0, -1).Result()
	if err != nil {
		return nil, err
	}

	var executions []*model.Execution
	for _, id := range execIDs {
		vals, err := r.Redis.HGetAll(ctx, "execution:"+id).Result()
		if err != nil || len(vals) == 0 {
			continue
		}
		exec := &model.Execution{
			ID:         vals["id"],
			FunctionID: vals["functionId"],
			Status:     model.Status(vals["status"]),
		}
		if result, ok := vals["result"]; ok && result != "" {
			exec.Result = &result
		}
		executions = append(executions, exec)
	}

	return executions, nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context) ([]*model.Schedule, error) {
	ids, err := r.Redis.SMembers(ctx, "schedules").Result()
	if err != nil {
		return nil, err
	}

	var schedules []*model.Schedule
	for _, id := range ids {
		vals, err := r.Redis.HGetAll(ctx, "schedule:"+id).Result()
		if err != nil || len(vals) == 0 {
			continue
		}
		schedules = append(schedules, &model.Schedule{
			ID:         vals["id"],
			FunctionID: vals["functionId"],
			Cron:       vals["cron"],
		})
	}

	return schedules, nil
}

// DeadLetterJobs is the resolver for the deadLetterJobs field.
func (r *queryResolver) DeadLetterJobs(ctx context.Context) ([]*model.DeadLetterJob, error) {
	items, err := r.Redis.LRange(ctx, "dead_letter_queue", 0, -1).Result()
	if err != nil {
		return nil, err
	}

	var jobs []*model.DeadLetterJob
	for _, item := range items {
		var entry shared.DeadLetterEntry
		if err := json.Unmarshal([]byte(item), &entry); err != nil {
			continue
		}
		jobs = append(jobs, &model.DeadLetterJob{
			ExecutionID: entry.ExecutionID,
			FunctionID:  entry.FunctionID,
			Language:    entry.Language,
			Error:       entry.Error,
			Retries:     int32(entry.Retries),
		})
	}

	return jobs, nil
}

// FunctionLogs is the resolver for the functionLogs field.
func (r *subscriptionResolver) FunctionLogs(ctx context.Context, executionID string) (<-chan *model.Log, error) {
	ch := make(chan *model.Log, 100)

	go func() {
		defer close(ch)

		pubsub := r.Redis.Subscribe(ctx, "logs:"+executionID)
		defer func() { _ = pubsub.Close() }()

		for msg := range pubsub.Channel() {
			var entry shared.LogEntry
			if err := json.Unmarshal([]byte(msg.Payload), &entry); err != nil {
				continue
			}
			if entry.Done {
				return
			}
			ch <- &model.Log{
				ExecutionID: executionID,
				Message:     entry.Message,
				Level:       entry.Level,
				Timestamp:   entry.Timestamp,
			}
		}
	}()

	return ch, nil
}

func (r *Resolver) Mutation() MutationResolver     { return &mutationResolver{r} }
func (r *Resolver) Query() QueryResolver           { return &queryResolver{r} }
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
