// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type DeadLetterJob struct {
	ExecutionID string `json:"executionId"`
	FunctionID  string `json:"functionId"`
	Language    string `json:"language"`
	Error       string `json:"error"`
	Retries     int32  `json:"retries"`
}

type Execution struct {
	ID         string  `json:"id"`
	FunctionID string  `json:"functionId"`
	Status     Status  `json:"status"`
	Result     *string `json:"result,omitempty"`
}

type Function struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Language  Language `json:"language"`
	Code      string   `json:"code"`
	CreatedAt string   `json:"createdAt"`
}

type Log struct {
	ExecutionID string `json:"executionId"`
	Message     string `json:"message"`
	Level       string `json:"level"`
	Timestamp   string `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type Schedule struct {
	ID         string `json:"id"`
	FunctionID string `json:"functionId"`
	Cron       string `json:"cron"`
}

type Subscription struct {
}

type Language string

const (
	LanguagePython Language = "PYTHON"
	LanguageNodejs Language = "NODEJS"
	LanguageGo     Language = "GO"
)

var AllLanguage = []Language{
	LanguagePython,
	LanguageNodejs,
	LanguageGo,
}

func (e Language) IsValid() bool {
	switch e {
	case LanguagePython, LanguageNodejs, LanguageGo:
		return true
	}
	return false
}

func (e Language) String() string {
	return string(e)
}

func (e *Language) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Language(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Language", str)
	}
	return nil
}

func (e Language) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Language) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Language) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Status string

const (
	StatusQueued    Status = "QUEUED"
	StatusRunning   Status = "RUNNING"
	StatusCompleted Status = "COMPLETED"
	StatusFailed    Status = "FAILED"
)

var AllStatus = []Status{
	StatusQueued,
	StatusRunning,
	StatusCompleted,
	StatusFailed,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusQueued, StatusRunning, StatusCompleted, StatusFailed:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
